### ISSUE TITLE
Definir el cronograma

### ISSUE THREAD

**Issue by SamuelHenao404** [afgarnicar/App-Dietas-Saludables#19]
Tenemos que definir el cronograma, ósea cuando hacemos cada cosa, horarios de reunión, etc...

**Comment by SamuelRivero50** [comment]
El cronograma de trabajo es flexible según las entregas que tengamos así que se definen las tareas de cada uno de los integrantes del proyecto y cada uno va realizando su trabajo y una vez por semana tenemos reuniones de acuerdo a la disponibilidad de cada integrante para llevar un seguimiento.
