### ISSUE TITLE
Definir estado inicial, final y métodos

### ISSUE THREAD

**Issue by afgarnicar** [afgarnicar/App-Dietas-Saludables#2]
Esta tarea debe estar lista antes del 11/08/23

**Comment by SamuelRivero50** [comment]
Estado inicial: Hemos entendido el problema que queremos abordar y definimos la solución para comprender los pasos a seguir en nuestro proyecto. Estamos en el proceso de planeación en el cual iremos desarrollando los diferentes aspectos de nuestro proyecto que tenemos que trabajar.

Estado final: Esperamos tener un proyecto exitoso y funcional al cual se le hará su debido mantenimiento para seguir progresando en él, tendremos una visión aún más amplia del problema y estaremos en busca de solucionar muchos más en la misma área.

Métodos: Al ser el método de cascada (Waterfall) no tan flexible para el proyecto que estamos trabajando, hemos decidido usar la metodología ágil (Scrum) ya que con esta podemos mandar partes de nuestro proyecto para ser revisadas y poco a poco ir corrigiendo durante el desarrollo pero teniendo partes funcionales con anterioridad antes de finalizarlo, también nos parece que es la adecuada a nivel de organización en nuestro proyecto debido a que existe una constante comunicación durante el proyecto y retroalimentación sobre cada cosa que se realiza.
