### ISSUE TITLE
Definir roles y responsabilidades

### ISSUE THREAD

**Issue by SamuelHenao404** [afgarnicar/App-Dietas-Saludables#24]
Definamos los roles entre los 3 y entre las entregas.

**Comment by afgarnicar** [comment]
Cada integrante del grupo va a cumplir 5 roles, Analista, Diseñador, Desarrollador, Administrador y Tester. Todo esto con el fin de que cada integrante pueda aportar de la mejor forma posible durante el proceso de planificación, desarrollo y mantenimiento del producto final.

**Comment by afgarnicar** [comment]
Cada integrante del grupo va a cumplir 5 roles, Analista, Diseñador, Desarrollador, Administrador y Tester. Todo esto con el fin de que cada integrante pueda aportar de la mejor forma posible durante el proceso de planificación, desarrollo y mantenimiento del producto final.
