### ISSUE TITLE
Definir recursos necesarios

### ISSUE THREAD

**Issue by SamuelHenao404** [afgarnicar/App-Dietas-Saludables#27]
¿Qué vamos a necesitar para crear nuestro proyecto?
-Recursos
-Software necesario
-conocimientos y ayudas en lenguaje de programación
-etc...

**Comment by SamuelRivero50** [comment]
Vamos a necesitar un par de computadores para realizar el proyecto, software como GenMyModel, StormBoard, GuiGenie, etc. También necesitaremos conocimientos para crear la interfaz de usuario, diagramas de flujo, algoritmos y de lenguajes de programación como Java.
