### ISSUE TITLE
Definir las partes del análisis y solución del problema

### ISSUE THREAD

**Issue by SamuelRivero50** [afgarnicar/App-Dietas-Saludables#3]
Esta tarea debe estar lista antes del 11/08/23

**Comment by afgarnicar** [comment]
La problemática a tratar es salud y bienestar, específicamente el tema relacionado con la alimentación y nutrición. 

Con esta temática es necesario analizar puntos claves como lo serian las causas de obesidad, y todo lo que la obesidad implica en la vida de las personas. Por ejemplo, tener una buena conciencia sobre su salud, ya que el peso de las personas tiene mucho que ver con su salud, ya que el peso tiene el potencial de afectar la salud si no esta bien controlado.

La mejor forma de solucionar este problema es mediante un buen seguimiento y control del peso, promoviendo un estilo de vida mas saludable, evitando todo tipo de efectos negativos que puede provocar un peso que no sea el adecuado.
