### ISSUE TITLE
Definir las características del usuario

### ISSUE THREAD

**Issue by SamuelHenao404** [afgarnicar/App-Dietas-Saludables#30]
Demas que las personas que quieran una rutina chill, no?

**Comment by SamuelRivero50** [comment]
**Definimos dos tipos de usuarios que podrían usar nuestro sistema.**

**Juan:** 

Edad: 30
Estatura: 1.60
Peso: 70kg
IMC = 27.3 (Sobrepeso)
Género masculino
Tiene una mala alimentación
Quiere cambiar sus hábitos alimenticios para mejorar su salud tanto físicamente como mentalmente
Busca prevenir posibles enfermedades que se derivan de malos hábitos alimenticios

**Maria:** 

Edad: 23
Estatura: 1.8
IMC = 16.9 (Bajo peso)
Género femenino
Alimentación insuficiente
Malos hábitos alimenticios 
Falta de conocimiento sobre lo que su peso implica para su salud
Tiene la intención de aplicar la dieta recomendada por la app, para llegar a un IMC de peso normal, y así mantener un estilo de vida saludable

**Comment by SamuelRivero50** [comment]
**Definimos dos tipos de usuarios que podrían usar nuestro sistema.**

**Juan:** 

Edad: 30
Estatura: 1.60
Peso: 70kg
IMC = 27.3 (Sobrepeso)
Género masculino
Tiene una mala alimentación
Quiere cambiar sus hábitos alimenticios para mejorar su salud tanto físicamente como mentalmente
Busca prevenir posibles enfermedades que se derivan de malos hábitos alimenticios

**Maria:** 

Edad: 23
Estatura: 1.8
IMC = 16.9 (Bajo peso)
Género femenino
Alimentación insuficiente
Malos hábitos alimenticios 
Falta de conocimiento sobre lo que su peso implica para su salud
Tiene la intención de aplicar la dieta recomendada por la app, para llegar a un IMC de peso normal, y así mantener un estilo de vida saludable
