### ISSUE TITLE
Definir las características del hardware

### ISSUE THREAD

**Issue by SamuelHenao404** [afgarnicar/App-Dietas-Saludables#31]
Creo que mi computador basta, pero eso hay que hablarlo.

**Comment by SamuelRivero50** [comment]
- Sistema Operativo Android.

- CPU de un Solo Núcleo.

- 512 MB de RAM.

- Almacenamiento Interno Mínimo de 50 MB.

- Resolución de Pantalla Baja a Media.

- Conectividad 3G/4G y Wi-Fi.

-Sensores Básicos.

- Accesibilidad.

- Compatibilidad con Versiones Antiguas de Android.
