### ISSUE TITLE
Definir los modelos de los requisitos de datos, flujo de información y control

### ISSUE THREAD

**Issue by SamuelHenao404** [afgarnicar/App-Dietas-Saludables#32]
Si.

**Comment by SamuelRivero50** [comment]
**Modelo de Requisitos de Datos:**

1. Usuario:

-Nombre
-Apellido
-Edad
-Género
-Peso
-Altura
-IMC (calculado automáticamente)
-Objetivo de peso (por ejemplo, perder peso, mantener peso, ganar peso)
-Restricciones alimentarias (si las hay, como alergias o preferencias dietéticas)

2. Plan de Dieta:

-Nombre del plan
-Descripción del plan
-Lista de comidas (desayuno, almuerzo, cena y refrigerios) asociadas al plan
-Información nutricional para cada comida (calorías, proteínas, carbohidratos, grasas, etc.)

3. Historial de IMC:

-Registro de IMC a lo largo del tiempo para cada usuario
-Fecha y hora de registro

**Modelo de Flujo de Información:**


1. Registro de Usuario:

-Los usuarios ingresan sus datos personales y objetivos.
-La aplicación calcula automáticamente el IMC.
-Los datos se almacenan en el perfil del usuario.

2. Selección de Plan de Dieta:

Los usuarios eligen un plan de dieta basado en sus objetivos y restricciones alimentarias.
El plan seleccionado se asocia con el perfil del usuario.

3. Seguimiento de la Dieta:

Los usuarios registran las comidas y las cantidades que consumen en su plan de dieta.
La aplicación realiza un seguimiento de las calorías y otros valores nutricionales consumidos.

4. Registro de IMC:

-Los usuarios registran su IMC regularmente.
-La aplicación guarda el historial de IMC y puede mostrar gráficos de progreso.

5. Generación de Recomendaciones:

-Basándose en los datos del usuario y su progreso, la aplicación puede generar recomendaciones para ajustar el plan de dieta.

**Modelo de Control:**

1. Autenticación y Registro:

-Control de acceso a la aplicación mediante autenticación.
-Validación de datos de registro para evitar información incorrecta.

2. Selección de Plan de Dieta:

-Interfaz para que los usuarios seleccionen un plan de dieta.
-Lógica para asociar el plan seleccionado con el perfil del usuario.

3. Registro de Comidas:

-Formularios o pantallas para registrar comidas consumidas.
-Cálculos de valores nutricionales en función de los datos ingresados.

4. Gestión del Historial de Pesos:

-Interfaz para registrar y visualizar el historial de pesos.
-Lógica para almacenar y procesar los datos de peso.

5. Generación de Recomendaciones:

- Algoritmos para generar recomendaciones dietéticas basadas en el progreso del usuario y los objetivos.
