### ISSUE TITLE
Definir el modelo del comportamiento operativo

### ISSUE THREAD

**Issue by SamuelHenao404** [afgarnicar/App-Dietas-Saludables#33]

**Comment by afgarnicar** [comment]
El comportamiento operativo se basa en los siguientes pasos:
1. Registro de usuario
2. Inicio de sesión
3. Selección de condiciones medicas
4. Calculo del IMC
5. Generación de recomendaciones
6. Seguimiento y visualización del proceso
7. Alertas y recordatorios dentro de la app
8. Mantenimiento
