### ISSUE TITLE
Buscar y proponer alternativas de solución

### ISSUE THREAD

**Issue by afgarnicar** [afgarnicar/App-Dietas-Saludables#5]
Esta tarea debe estar lista antes del 11/08/23

**Comment by SamuelHenao404** [comment]
La problemática del mal habito alimenticio es un problema extenso y notorio en la sociedad actual, en base de esta problemática se discutió y se planteo una posible solución: 
Una app de Dietas Saludables que busca promover la educación sobre una alimentación saludable y crear una ruta alimenticia para así brindar ayuda a esa problemática; Se plantea añadir otras características a esta app para así mejorar su eficacia.
